### ISSUE TITLE
微信登录的说明

### ISSUE THREAD

**Issue by lyndon1115** [skiy/skiy_wx_login#1]
由于xiuno闭站，作者skiy.net的站点数据丢失，现在从百度cache捞回来本插件的使用说明如下：

> 
微信登录 for Xiuno BBS 4.x
作品集	Skiychan 8个月前 (04-02) 1694浏览 0评论
参考官网的 QQ 登录功能弄了一个微信登录的。

使用教程如下：

微信公众号必须是已认证的。

1. 登录微信公众平台；

2. 左下角 “开发 => 基本配置” 处获取 “开发者ID(AppID)” 和 “开发者密码(AppSecret)”

3. “公众号设置 => 功能设置” 配置 “网页授权域名”。

安装插件后，点击插件的“设置” 配置微信的 “开发者ID(AppID)” 和 “开发者密码(AppSecret)”；

使用微信打开网站

1. 未登录用户直接登录会新建一个新用户；

2. 如果已注册用户，并且登录，可在“个人中心” 页 “申请绑定微信”。

3. 绑定微信后不可解除绑定（因为如果是直接用微信登录创建的新用户，密码及邮箱无法修改）。

注意：

卸载插件时，会删除微信与用户UID绑定的表。如果有用户是直接使用微信登录（新建用户），则会导致该用户无法再正常登录。切记！！！

GitHub开源地址：https://github.com/skiy/xiuno-plugins/blob/master/skiy_wx_login

插件地址：http://plugin.xiuno.com/plugin-read-skiy_wx_login.htm
插件说明：http://bbs.xiuno.com/thread-21280.htm

转载请注明：SKIY开发笔记 » 微信登录 for Xiuno BBS 4.x

继续浏览有关 xiunoxiuno插件微信登录 的文章

**Comment by skiy** [comment]
站点数据虽然丢失了，但是文档还是有的，只是迁移到 **学习笔记** 分站点了而已：https://note.skiy.net/thread-11.htm
